### ISSUE TITLE
[Epic]  v2 Roadmap Epics

### ISSUE THREAD

**Issue by alfsuse** [fuseml/fuseml#145]
This Epic represents the sum of all Epics that should be included in the v2 of FuseML. Aside from Epics, issues regarding features and enhancements proposals collected from the development of the previous version are also included, some of which could be linked to the existing Epics. Only Epics and stories that will be marked in the list are agreed to be worked in the v2, everything else will be moved back to backlog after the planning meetings. 

- Epics (in order of decreasing priority)

  - [x] #161  Installer: add official support to install extensions 
  - [x] #152 NVIDIA Triton Infernece Server
  - [x] #153 Intel Inference Engine
  - [x] #21 FuseML Central Recipe Store
  - [x] #20 Fuseml UI
  - [x] #19  Design Architecture
  - [x] #155 Project Promotion and Community building

- Features
  - [x] #69 Workflow templates. Related to #151 #150 #21. (epic candidate)
  - [x] #74 Registry to store fuseml extensions (i.e. MLFlow URL, S3 backends) . Related to #21. (epic candidate) 
  - [x] #68 Persistent state for fuseml components (epic candidate)
  - [x] #120 Advanced workflow life-cycle actions

- Enhancements
  - [x] #121 Terminate obsolete workflow runs automatically
  - [x] #116 CLI: Live-watch a running workflow
  - [x] #162 MLFlow extension: reuse previously built environment image. Related to #152 #153.

**Comment by stefannica** [comment]
V2 has been released
