### ISSUE TITLE
[Epic] Placeholder for next FuseML releases

### ISSUE THREAD

**Issue by alfsuse** [fuseml/fuseml#156]
# **This is a placeholder the list here represent what has been filtered out from the current release but still may be part of a future release**

This Epic represents the sum of all Epics that should be included in the next release of FuseML. Aside from Epics, issues regarding features and enhancements proposals collected from the development of the previous version are also included, some of which could be linked to the existing Epics. Only Epics and stories that will be marked in the list are agreed to be worked in the next, everything else will be moved back to backlog after the planning meetings. 

- Epics (in order of decreasing priority)

  - [ ] #150 Argo Workflow engine support
  - [ ] #147 Minio Artifacts Url
  - [ ] #151 Generic workflow step
  - [ ] #146 Multi-Steps Workflow
  - [ ] #154 Data Source support
  - [ ] #148 Notebook as UI

- Features
  - [ ] #119 (external) TLS support (epic candidate)
  - [ ] #62 FuseML users
  - [ ] #85 Retention policies and garbage collection for workflows & byproducts (epic candidate)

- Enhancements
  - [ ] #92 CLI: easier way to push codeset updates
  - [ ] #122 Workflow update
  - [ ] #115 Add step status info to workflow runs
  - [ ] #95 installer: customize configuration
  - [ ] #94 installer: enhanced "info" command
  - [ ] #84 Control timeout values for workflows
